env:
  global:
    - CONAN_REFERENCE: log4cplus/1.2.0
    - CONAN_USERNAME: salessandri
    - CONAN_LOGIN_USERNAME: salessandri
    - CONAN_CHANNEL: testing
    - CONAN_UPLOAD: 'https://api.bintray.com/conan/salessandri/conan'
    - CONAN_STABLE_BRANCH_PATTERN: release/*
    - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
linux:
  os: linux
  sudo: required
  language: python
  python: '3.6'
  services: &ref_0
    - docker
osx:
  os: osx
  language: generic
matrix:
  include:
    - os: linux
      sudo: required
      language: python
      python: '3.6'
      services: *ref_0
      env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49
    - os: linux
      sudo: required
      language: python
      python: '3.6'
      services: *ref_0
      env: CONAN_GCC_VERSIONS=5.4 CONAN_DOCKER_IMAGE=lasote/conangcc54
    - os: linux
      sudo: required
      language: python
      python: '3.6'
      services: *ref_0
      env: CONAN_GCC_VERSIONS=6.3 CONAN_DOCKER_IMAGE=lasote/conangcc63
    - os: linux
      sudo: required
      language: python
      python: '3.6'
      services: *ref_0
      env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39
    - os: linux
      sudo: required
      language: python
      python: '3.6'
      services: *ref_0
      env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40
    - os: osx
      language: generic
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3
    - os: osx
      language: generic
      osx_image: xcode8.2
      env: CONAN_APPLE_CLANG_VERSIONS=8.0
    - os: osx
      language: generic
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1
    - os: osx
      language: generic
      osx_image: xcode9
      env: CONAN_APPLE_CLANG_VERSIONS=9.0
install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh
script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
